# SPDX-FileCopyrightText: 2026 startclean contributors <https://github.com/P4suta/startclean/graphs/contributors>
# SPDX-License-Identifier: MIT OR Apache-2.0

version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - bidichk
    - bodyclose
    - contextcheck
    - durationcheck
    - errorlint
    - errname
    - exhaustive
    - fatcontext
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocritic
    - gomoddirectives
    - gosec
    - makezero
    - misspell
    - modernize
    - musttag
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - reassign
    - staticcheck
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - wastedassign
formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
